url: https://api.trakt.tv
client_id: "trakt_client_id"
client_secret: "trakt_client_secret"
tokens:
  access_token: "trakt_access_token"
  refresh_token: "trakt_refresh_token"
  token_last_updated_on: "trakt_token_last_updated_on"
all_headers:
  Content-Type: application/json
  trakt-api-version: "2"
  trakt-api-key: CLIENT_ID_REPLACE_STRING
  Authorization: Bearer TOKEN_REPLACE_STRING
token_headers: 
  Content-Type: application/json
endpoints:

  Recommended Shows:
    url: https://api.trakt.tv/recommendations/shows
    headers: all
    params:
      ignore_collected: false
      ignore_watchlisted: true
      extended: full
    results_to_return: 300
  
  History:
    url: https://api.trakt.tv/sync/history
    headers: all
    params:
      extended: full
    results_to_return: 10000